{% set name = "lume-genesis" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/slaclab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3e1f0d876f9e158dbcefb20fe341355d2f29e698e29be9e7a33ce0233a700b49

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - eval-type-backport
    - genesis2
    - genesis4 >=4.6.6
    - jinja2
    - lark
    - lume-base
    - matplotlib
    - numpy
    - openpmd-beamphysics
    - prettytable
    - psutil
    - pydantic >2
    - pydantic-settings
    - scipy
    - typing-extensions

test:
  imports:
    - genesis
  requires:
    - pytest
    - pytest-cov
  source_files:
    - docs
    - genesis
    - pyproject.toml
  commands:
    - pytest -v

about:
  home: https://github.com/slaclab/lume-genesis
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Genesis tools for use in LUME
  description: |
    Genesis tools for use in LUME.

extra:
  recipe-maintainers:
    - balticfish
    - ChristopherMayes
    - ken-lauer
